spring:
  application:
    name: qcmservice
  config:
    import: "optional:configserver:https://qcm-configserver.onrender.com/qcmservice/default"
  datasource:
    url: jdbc:mysql://localhost:3306/qcm
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
